version: "3.6"
services:
  nextjs:
    stdin_open: true # docker run -i
    tty: true # docker run -t
    container_name: sentilabelling
    working_dir: /src/app/
    build:
      context: "../"
    command: npm run dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ../:/src/app
      - /src/app/node_modules
      - /src/app/.next
    ports:
      - 80:80
  localstack:
    container_name: localstack
    image: localstack/localstack-light
    ports:
      - 127.0.0.1:4566:4566 # LocalStack Gateway
      - 127.0.0.1:4510-4559:4510-4559 # external services port range
    env_file:
      - .env
    environment:
      - DEBUG=${DEBUG-}
      - PERSISTENCE=${PERSISTENCE-1}
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-local}
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3
      - EAGER_SERVICE_LOADING=1
      - LAMBDA_REMOTE_DOCKER=false
    volumes:
      - /tmp/senti_labelling/localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
      - ./initaws:/docker-entrypoint-initaws.d
  db:
    image: postgres
    restart: always
    env_file:
      - ./.env
    ports:
      - 5432:5432
